# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 711b9f3ac2c9b4802759f16e4b3a3585bc718ddadbc78317e51590c2de3f641ce128922e3c474b43462dd0096d7e397df84f66a949b92c9ac219747a5c7745ea

test:
  secret_key_base: 75226f006ce785361d89342bb6d01265c71df71efda39577bdc6f6121062562460810d0dc85b3215715d514763eedf54bfc6697cc76a975bc37fbdff746eea03

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
